[package]
name = "man-completions"
version = "0.1.0"
description = "Generate completions for Zsh and other shells from manpages"
keywords = ["shell"]
repository = "https://github.com/ysthakur/man-completions"
homepage = "https://github.com/ysthakur/man-completions"
license = "MIT"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
clap = { version = "4.3", features = ["derive"] }
flate2 = "1.0"
regex = "1.9"

[dev-dependencies]
assert_cmd = "2.0"

[[bin]]
name = "man-completions"
path = "src/main.rs"
