name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          package-name: man-completions
          release-type: rust
      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}
        # Publish to Cargo if release created
      - run: cargo publish --verbose --token ${{ secrets.CARGO_REGISTRY_TOKEN }}
        if: ${{ steps.release.outputs.release_created }}
